name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Resolve dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Build docs
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist

      # - name: Publish packages
      #   run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
